In [5]:
import numpy  as np
from matplotlib import pyplot as plt
import torch

In [2]:
# 2.1.1 Create a 1D tensor with values from 0 to 11
x = torch.arange(12)
print(x.device)
print("x : ",x)  # tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
print("x shape: ",x.shape)  # torch.Size([12])
print("x ndim: ",x.ndim)  # 1
print("x numel: ",x.numel())  # 12
x_reshaped = x.reshape(3, 4)
print("x reshaped : ",x_reshaped)
x_zeros = torch.zeros((2, 3, 4))
print("x zeros : ",x_zeros)  # tensor of shape (2, 3, 4) filled with zeros
x_ones = torch.ones((2, 3, 4))
print("x ones : ",x_ones)  # tensor of shape (2, 3, 4) filled with ones
x_random = torch.randn((3, 4))
print("x random : ",x_random)  # tensor of shape (3, 4) with random values
x_full = torch.full((2, 3), 7)
print("x full : ",x_full)  # tensor of shape (2, 3) filled with 7s
x_eye = torch.eye(3)
print("x eye : ",x_eye)  # 3x3 identity matrix

cpu
x :  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x shape:  torch.Size([12])
x ndim:  1
x numel:  12
x reshaped :  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
x zeros :  tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
x ones :  tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
x random :  tensor([[ 0.8549,  1.4881,  1.4319, -1.0105],
        [-0.6650,  0.3311, -1.7139,  0.4628],
        [ 1.5004,  0.0356,  0.1921,  0.4060]])
x full :  tensor([[7, 7, 7],
        [7, 7, 7]])
x eye :  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [3]:
# 2.1.2 Basic tensor operations
X = torch.tensor([1.0,2,4,8])
Y = torch.tensor([2,2,2,2])
print("X + Y : ",X + Y)  # element-wise addition
print("X - Y : ",X - Y)  # element-wise subtraction
print("X * Y : ",X * Y)  # element-wise multiplication
print("X / Y : ",X / Y)  # element-wise division
print("X ** Y : ",X ** Y)  # element-wise exponentiation
print("X exp : ",torch.exp(X))  # element-wise exponential
print("X sum : ",X.sum())  # sum of all elements in X

Z = torch.arange(12, dtype=torch.float32).reshape(3, 4)
M = torch.tensor([[1.0, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("cat Z & M long rows: \n",torch.cat([Z, M], dim=0))  # concatenate along rows
print("cat Z & M along columns: \n",torch.cat([Z, M], dim=1))  # concatenate along columns

X + Y :  tensor([ 3.,  4.,  6., 10.])
X - Y :  tensor([-1.,  0.,  2.,  6.])
X * Y :  tensor([ 2.,  4.,  8., 16.])
X / Y :  tensor([0.5000, 1.0000, 2.0000, 4.0000])
X ** Y :  tensor([ 1.,  4., 16., 64.])
X exp :  tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
X sum :  tensor(15.)
cat Z & M long rows: 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
cat Z & M along columns: 
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
        [ 8.,  9., 10., 11.,  9., 10., 11., 12.]])


In [ ]:
# 2.1.3
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
print("a : ",a)
print("b : ",b)
print("a + b with Broadcasting :\n", a+b)
a_numpy = a.numpy
print("tensor to ndarray :\n",a_numpy)
m = np.arange(12).reshape(3,4)
m_tensor = torch.tensor(m)
print("ndarray to tensor :\n",m_tensor)

a :  tensor([[0],
        [1],
        [2]])
b :  tensor([[0, 1]])
a + b with Broadcasting :
 tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor to ndarray :
 <built-in method numpy of Tensor object at 0x0000022C7E298F50>
ndarray to tensor :
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
